#!/bin/zsh
docker run -it --rm --name pydev -v /home/andy/ws/new/newd/tests:/home/andy/ws/new/newd/tests -v /home/andy/.config/sublime-text-3/Cache/PyTest/:/home/andy/.config/sublime-text-3/Cache/PyTest/ -w /home/andy/ws/new/newd/tests pydev pytest -vv $1
